version: '3.4'
services:
  archipel-ui.public.dappnode.eth:
    build: ./build
    image: 'archipel-ui.public.dappnode.eth:1.0.2'
    restart: always
    volumes:
      - 'archipelpublicdappnodeeth_config:/config:ro'
volumes:
  archipelpublicdappnodeeth_config:
    external: true
